name: Go Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          args: --verbose --timeout=5m
          skip-pkg-cache: true
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run tests
        run: go test -race ./...
  integration-test:
    strategy:
      matrix:
        dialect: [mysql, postgres, sqlite, sqlserver, spanner]
        go: ['1.23', '1.24']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: '${{ secrets.ATLAS_TOKEN }}'
          version: 'beta'
      - working-directory: internal/testdata
        run: |
          atlas migrate diff --env gorm --var dialect=${{ matrix.dialect }}
      - name: Migrate Diff Circular Foreign keys
        working-directory: internal/testdata/circularfks
        run: |
          atlas migrate diff --env gorm --var dialect=${{ matrix.dialect }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env gorm' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
          fi
